Update Dockerfile and Vagrantfile for the classroom exercises
udacity/nd064_course_1 pull request #75
Opened 2022-01-20 16:43 UTC by SudKul

2022-01-26 13:43 UTC, AugustasV commented on .gitignore
> +.vagrant/
add a newline at the end of the file

2022-02-03 12:33 UTC, kgamanji requested changes
Looks good! Just minor changes that you can easily apply as part of the review. 

Otherwise LGTM

2022-02-03 12:33 UTC, kgamanji commented on exercises/README.md
> +**Note** that the specified `config.vm.box_version` in the Vagrantfile updates with time. You will have to change it from 242 shown in the video demo above to a newer version. When a particular versi
```suggestion
**Note**: the specified `config.vm.box_version` in the Vagrantfile updates with time. You will have to change it from `212` shown in the demo video above to a newer version. When a particular version used in Vagrantfile becomes deprecated, the command prompt will show you all available newer versions. 
```

2022-02-03 12:33 UTC, kgamanji commented on .gitignore
> +.vagrant/
```suggestion
.vagrant/

```

2022-02-03 12:33 UTC, kgamanji commented on exercises/README.md
> +└── python-helloworld  # Docker Walkthrough code
```suggestion
└── python-helloworld  # Docker walkthrough code  
```

2022-02-04 18:04 UTC, kgamanji commented on project/Vagrantfile
> +    inline: "sudo su - && zypper update && zypper install -y apparmor-parser"
Why is `apparmor-parser` needed?

2022-02-04 18:33 UTC, kgamanji commented on project/Vagrantfile
> +    inline: "sudo su - && zypper update && zypper install -y apparmor-parser"
Makes sense, as it's required with the higher versions: https://github.com/rancher/k3os/issues/702

2022-02-07 13:22 UTC, SudKul commented
Thank you @kgamanji and @AugustasV for your review.

2022-02-07 13:22 UTC, merged